import Mathlib.Data.Matrix.Basic
import Mathlib.Data.ZMod.Basic
import Mathlib.Tactic.FinCases

/-! Exact data from AME_9_6_complete_proof_20260922.md.
Generated by scripts/generate_data.py. No numerical approximations. -/
set_option maxRecDepth 8192
namespace AME96
open scoped BigOperators

def G : Matrix (Fin 9) (Fin 9) (ZMod 2) :=
  ![![0, 1, 1, 1, 1, 1, 1, 1, 1],
  ![1, 0, 0, 0, 0, 1, 0, 1, 1],
  ![1, 0, 0, 0, 0, 1, 1, 1, 0],
  ![1, 0, 0, 0, 1, 0, 1, 0, 1],
  ![1, 0, 0, 1, 0, 0, 0, 1, 1],
  ![1, 1, 1, 0, 0, 0, 1, 1, 1],
  ![1, 0, 1, 1, 0, 1, 0, 0, 1],
  ![1, 1, 1, 0, 1, 1, 0, 0, 0],
  ![1, 1, 0, 1, 1, 1, 1, 0, 0]]

def B : Matrix (Fin 9) (Fin 9) (ZMod 3) :=
  ![![0, 0, 2, 1, 2, 1, 0, 0, 2],
  ![0, 0, 1, 0, 0, 1, 1, 1, 1],
  ![0, 2, 0, 1, 0, 1, 0, 1, 1],
  ![1, 0, 0, 0, 2, 1, 2, 0, 0],
  ![0, 0, 0, 0, 0, 0, 0, 0, 0],
  ![0, 0, 0, 0, 0, 0, 0, 0, 0],
  ![0, 0, 0, 0, 0, 0, 0, 0, 0],
  ![0, 0, 0, 0, 0, 0, 0, 0, 0],
  ![0, 0, 0, 0, 0, 0, 0, 0, 0]]

def H : Matrix (Fin 9) (Fin 9) (ZMod 3) :=
  ![![0, 2, 1, 0, 0, 0, 0, 0, 0],
  ![2, 0, 0, 1, 0, 0, 0, 0, 0],
  ![1, 0, 0, 1, 0, 0, 0, 0, 0],
  ![0, 1, 1, 0, 0, 0, 0, 0, 0],
  ![0, 0, 0, 0, 0, 0, 0, 0, 0],
  ![0, 0, 0, 0, 0, 0, 0, 0, 0],
  ![0, 0, 0, 0, 0, 0, 0, 0, 0],
  ![0, 0, 0, 0, 0, 0, 0, 0, 0],
  ![0, 0, 0, 0, 0, 0, 0, 0, 0]]

def C : Matrix (Fin 9) (Fin 9) (ZMod 3) :=
  ![![0, 2, 0, 0, 0, 2, 1, 2, 1],
  ![2, 0, 0, 2, 1, 2, 0, 1, 0],
  ![0, 0, 0, 0, 1, 2, 0, 1, 1],
  ![0, 2, 0, 0, 0, 1, 0, 1, 1],
  ![0, 1, 1, 0, 0, 1, 2, 2, 1],
  ![2, 2, 2, 1, 1, 0, 1, 2, 1],
  ![1, 0, 0, 0, 2, 1, 0, 1, 1],
  ![2, 1, 1, 1, 2, 2, 1, 0, 1],
  ![1, 0, 1, 1, 1, 1, 1, 1, 0]]

theorem G_symmetric (i j : Fin 9) : G i j = G j i := by
  fin_cases i <;> fin_cases j <;> rfl
theorem G_diagonal : ∀ i, G i i = 0 := by decide +kernel
theorem H_symmetric (i j : Fin 9) : H i j = H j i := by
  fin_cases i <;> fin_cases j <;> rfl
theorem H_diagonal : ∀ i, H i i = 0 := by decide +kernel
theorem C_symmetric (i j : Fin 9) : C i j = C j i := by
  fin_cases i <;> fin_cases j <;> rfl
theorem C_diagonal : ∀ i, C i i = 0 := by decide +kernel

end AME96
