import AME96.CutData

/-! Generated by scripts/generate_fast_checks.py. Each proof specializes the
finite data before invoking the kernel, avoiding repeated indexing of the big table. -/
namespace AME96
open Matrix
set_option maxHeartbeats 0
set_option maxRecDepth 65536

private theorem compatibleCase000 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 0) (cutOutside 0) d (cutCompatible 0 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 2, 3] ![4, 5, 6, 7, 8] d
    ((![![0, 2, 0, 1], ![0, 1, 0, 0], ![1, 2, 0, 1], ![0, 1, 2, 1]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase001 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 1) (cutOutside 1) d (cutCompatible 1 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 2, 4] ![3, 5, 6, 7, 8] d
    ((![![2, 1, 1, 0], ![1, 0, 1, 0], ![0, 2, 0, 0], ![2, 2, 1, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase002 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 2) (cutOutside 2) d (cutCompatible 2 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 2, 5] ![3, 4, 6, 7, 8] d
    ((![![2, 0, 2, 0], ![2, 2, 2, 0], ![1, 2, 0, 0], ![1, 2, 1, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase003 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 3) (cutOutside 3) d (cutCompatible 3 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 2, 6] ![3, 4, 5, 7, 8] d
    ((![![0, 1, 1, 0], ![1, 0, 1, 0], ![1, 0, 2, 0], ![1, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase004 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 4) (cutOutside 4) d (cutCompatible 4 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 2, 7] ![3, 4, 5, 6, 8] d
    ((![![0, 0, 2, 0], ![1, 2, 2, 0], ![0, 0, 2, 0], ![0, 2, 1, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase005 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 5) (cutOutside 5) d (cutCompatible 5 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 2, 8] ![3, 4, 5, 6, 7] d
    ((![![1, 1, 1, 0], ![0, 0, 1, 0], ![2, 0, 2, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase006 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 6) (cutOutside 6) d (cutCompatible 6 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 3, 4] ![2, 5, 6, 7, 8] d
    ((![![1, 1, 1, 0], ![0, 2, 2, 0], ![2, 0, 2, 0], ![1, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase007 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 7) (cutOutside 7) d (cutCompatible 7 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 3, 5] ![2, 4, 6, 7, 8] d
    ((![![1, 1, 1, 0], ![2, 2, 1, 0], ![1, 2, 0, 0], ![2, 1, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase008 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 8) (cutOutside 8) d (cutCompatible 8 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 3, 6] ![2, 4, 5, 7, 8] d
    ((![![0, 0, 1, 0], ![2, 0, 2, 0], ![0, 2, 1, 0], ![1, 0, 1, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase009 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 9) (cutOutside 9) d (cutCompatible 9 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 3, 7] ![2, 4, 5, 6, 8] d
    ((![![2, 0, 1, 0], ![2, 2, 1, 0], ![1, 0, 1, 0], ![1, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase010 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 10) (cutOutside 10) d (cutCompatible 10 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 3, 8] ![2, 4, 5, 6, 7] d
    ((![![2, 0, 1, 0], ![0, 1, 1, 0], ![0, 1, 1, 0], ![1, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase011 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 11) (cutOutside 11) d (cutCompatible 11 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 4, 5] ![2, 3, 6, 7, 8] d
    ((![![1, 1, 0, 0], ![0, 1, 0, 0], ![0, 0, 0, 0], ![2, 1, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase012 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 12) (cutOutside 12) d (cutCompatible 12 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 4, 6] ![2, 3, 5, 7, 8] d
    ((![![2, 0, 0, 0], ![1, 0, 0, 0], ![1, 2, 0, 0], ![1, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase013 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 13) (cutOutside 13) d (cutCompatible 13 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 4, 7] ![2, 3, 5, 6, 8] d
    ((![![1, 0, 0, 0], ![1, 2, 0, 0], ![1, 0, 0, 0], ![0, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase014 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 14) (cutOutside 14) d (cutCompatible 14 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 4, 8] ![2, 3, 5, 6, 7] d
    ((![![1, 2, 0, 0], ![1, 1, 0, 0], ![1, 1, 0, 0], ![0, 1, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase015 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 15) (cutOutside 15) d (cutCompatible 15 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 5, 6] ![2, 3, 4, 7, 8] d
    ((![![2, 0, 0, 0], ![0, 1, 0, 0], ![2, 1, 0, 0], ![1, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

#check compatibleCase015

private theorem compatibleCase016 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 16) (cutOutside 16) d (cutCompatible 16 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 5, 7] ![2, 3, 4, 6, 8] d
    ((![![2, 0, 0, 0], ![2, 2, 0, 0], ![0, 0, 0, 0], ![1, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase017 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 17) (cutOutside 17) d (cutCompatible 17 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 5, 8] ![2, 3, 4, 6, 7] d
    ((![![0, 2, 0, 0], ![1, 0, 0, 0], ![1, 2, 0, 0], ![2, 1, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase018 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 18) (cutOutside 18) d (cutCompatible 18 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 6, 7] ![2, 3, 4, 5, 8] d
    ((![![1, 0, 0, 0], ![2, 2, 0, 0], ![0, 0, 0, 0], ![1, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase019 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 19) (cutOutside 19) d (cutCompatible 19 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 6, 8] ![2, 3, 4, 5, 7] d
    ((![![2, 2, 0, 0], ![2, 2, 0, 0], ![2, 1, 0, 0], ![1, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase020 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 20) (cutOutside 20) d (cutCompatible 20 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 1, 7, 8] ![2, 3, 4, 5, 6] d
    ((![![1, 0, 0, 0], ![2, 2, 0, 0], ![1, 2, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase021 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 21) (cutOutside 21) d (cutCompatible 21 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 2, 3, 4] ![1, 5, 6, 7, 8] d
    ((![![2, 0, 1, 0], ![1, 0, 2, 0], ![0, 2, 2, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase022 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 22) (cutOutside 22) d (cutCompatible 22 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 2, 3, 5] ![1, 4, 6, 7, 8] d
    ((![![2, 0, 2, 0], ![0, 0, 2, 0], ![0, 2, 2, 0], ![1, 0, 2, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase023 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 23) (cutOutside 23) d (cutCompatible 23 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 2, 3, 6] ![1, 4, 5, 7, 8] d
    ((![![0, 0, 0, 0], ![2, 0, 2, 0], ![0, 2, 0, 0], ![1, 0, 1, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase024 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 24) (cutOutside 24) d (cutCompatible 24 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 2, 3, 7] ![1, 4, 5, 6, 8] d
    ((![![0, 0, 2, 0], ![1, 0, 0, 0], ![0, 2, 0, 0], ![0, 0, 2, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase025 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 25) (cutOutside 25) d (cutCompatible 25 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 2, 3, 8] ![1, 4, 5, 6, 7] d
    ((![![0, 0, 2, 0], ![1, 0, 2, 0], ![0, 2, 1, 0], ![0, 0, 2, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase026 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 26) (cutOutside 26) d (cutCompatible 26 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 2, 4, 5] ![1, 3, 6, 7, 8] d
    ((![![2, 2, 0, 0], ![2, 2, 0, 0], ![1, 2, 0, 0], ![2, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase027 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 27) (cutOutside 27) d (cutCompatible 27 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 2, 4, 6] ![1, 3, 5, 7, 8] d
    ((![![1, 1, 0, 0], ![0, 2, 0, 0], ![1, 2, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase028 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 28) (cutOutside 28) d (cutCompatible 28 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 2, 4, 7] ![1, 3, 5, 6, 8] d
    ((![![2, 0, 0, 0], ![0, 1, 0, 0], ![0, 2, 0, 0], ![2, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase029 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 29) (cutOutside 29) d (cutCompatible 29 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 2, 4, 8] ![1, 3, 5, 6, 7] d
    ((![![1, 0, 0, 0], ![0, 1, 0, 0], ![1, 1, 0, 0], ![2, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase030 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 30) (cutOutside 30) d (cutCompatible 30 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 2, 5, 6] ![1, 3, 4, 7, 8] d
    ((![![1, 0, 0, 0], ![1, 1, 0, 0], ![2, 2, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase031 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 31) (cutOutside 31) d (cutCompatible 31 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 2, 5, 7] ![1, 3, 4, 6, 8] d
    ((![![1, 1, 0, 0], ![2, 2, 0, 0], ![2, 0, 0, 0], ![0, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

#check compatibleCase031

private theorem compatibleCase032 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 32) (cutOutside 32) d (cutCompatible 32 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 2, 5, 8] ![1, 3, 4, 6, 7] d
    ((![![1, 1, 0, 0], ![2, 1, 0, 0], ![2, 1, 0, 0], ![0, 1, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase033 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 33) (cutOutside 33) d (cutCompatible 33 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 2, 6, 7] ![1, 3, 4, 5, 8] d
    ((![![2, 1, 0, 0], ![0, 2, 0, 0], ![0, 0, 0, 0], ![2, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase034 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 34) (cutOutside 34) d (cutCompatible 34 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 2, 6, 8] ![1, 3, 4, 5, 7] d
    ((![![0, 2, 0, 0], ![0, 0, 0, 0], ![1, 2, 0, 0], ![2, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase035 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 35) (cutOutside 35) d (cutCompatible 35 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 2, 7, 8] ![1, 3, 4, 5, 6] d
    ((![![2, 2, 0, 0], ![0, 1, 0, 0], ![2, 0, 0, 0], ![0, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase036 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 36) (cutOutside 36) d (cutCompatible 36 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 3, 4, 5] ![1, 2, 6, 7, 8] d
    ((![![1, 1, 0, 0], ![0, 2, 0, 0], ![0, 2, 0, 0], ![2, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase037 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 37) (cutOutside 37) d (cutCompatible 37 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 3, 4, 6] ![1, 2, 5, 7, 8] d
    ((![![1, 2, 0, 0], ![0, 1, 0, 0], ![1, 0, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase038 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 38) (cutOutside 38) d (cutCompatible 38 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 3, 4, 7] ![1, 2, 5, 6, 8] d
    ((![![2, 0, 0, 0], ![2, 0, 0, 0], ![0, 1, 0, 0], ![1, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase039 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 39) (cutOutside 39) d (cutCompatible 39 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 3, 4, 8] ![1, 2, 5, 6, 7] d
    ((![![0, 1, 0, 0], ![1, 0, 0, 0], ![1, 1, 0, 0], ![0, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase040 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 40) (cutOutside 40) d (cutCompatible 40 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 3, 5, 6] ![1, 2, 4, 7, 8] d
    ((![![0, 1, 0, 0], ![1, 2, 0, 0], ![2, 0, 0, 0], ![1, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase041 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 41) (cutOutside 41) d (cutCompatible 41 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 3, 5, 7] ![1, 2, 4, 6, 8] d
    ((![![0, 1, 0, 0], ![1, 2, 0, 0], ![1, 0, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase042 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 42) (cutOutside 42) d (cutCompatible 42 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 3, 5, 8] ![1, 2, 4, 6, 7] d
    ((![![2, 0, 0, 0], ![1, 1, 0, 0], ![0, 2, 0, 0], ![1, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase043 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 43) (cutOutside 43) d (cutCompatible 43 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 3, 6, 7] ![1, 2, 4, 5, 8] d
    ((![![1, 0, 0, 0], ![0, 0, 0, 0], ![1, 2, 0, 0], ![1, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase044 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 44) (cutOutside 44) d (cutCompatible 44 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 3, 6, 8] ![1, 2, 4, 5, 7] d
    ((![![1, 0, 0, 0], ![2, 0, 0, 0], ![0, 2, 0, 0], ![1, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase045 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 45) (cutOutside 45) d (cutCompatible 45 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 3, 7, 8] ![1, 2, 4, 5, 6] d
    ((![![1, 0, 0, 0], ![2, 1, 0, 0], ![0, 1, 0, 0], ![1, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase046 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 46) (cutOutside 46) d (cutCompatible 46 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 4, 5, 6] ![1, 2, 3, 7, 8] d
    ((![![1, 0, 0, 0], ![0, 0, 0, 0], ![2, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase047 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 47) (cutOutside 47) d (cutCompatible 47 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 4, 5, 7] ![1, 2, 3, 6, 8] d
    ((![![1, 0, 0, 0], ![0, 0, 0, 0], ![2, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

#check compatibleCase047

private theorem compatibleCase048 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 48) (cutOutside 48) d (cutCompatible 48 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 4, 5, 8] ![1, 2, 3, 6, 7] d
    ((![![1, 0, 0, 0], ![0, 0, 0, 0], ![2, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase049 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 49) (cutOutside 49) d (cutCompatible 49 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 4, 6, 7] ![1, 2, 3, 5, 8] d
    ((![![1, 0, 0, 0], ![2, 0, 0, 0], ![0, 0, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase050 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 50) (cutOutside 50) d (cutCompatible 50 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 4, 6, 8] ![1, 2, 3, 5, 7] d
    ((![![2, 0, 0, 0], ![2, 0, 0, 0], ![0, 0, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase051 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 51) (cutOutside 51) d (cutCompatible 51 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 4, 7, 8] ![1, 2, 3, 5, 6] d
    ((![![0, 0, 0, 0], ![2, 0, 0, 0], ![1, 0, 0, 0], ![1, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase052 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 52) (cutOutside 52) d (cutCompatible 52 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 5, 6, 7] ![1, 2, 3, 4, 8] d
    ((![![1, 0, 0, 0], ![2, 0, 0, 0], ![1, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase053 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 53) (cutOutside 53) d (cutCompatible 53 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 5, 6, 8] ![1, 2, 3, 4, 7] d
    ((![![1, 0, 0, 0], ![2, 0, 0, 0], ![1, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase054 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 54) (cutOutside 54) d (cutCompatible 54 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 5, 7, 8] ![1, 2, 3, 4, 6] d
    ((![![0, 0, 0, 0], ![2, 0, 0, 0], ![2, 0, 0, 0], ![1, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase055 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 55) (cutOutside 55) d (cutCompatible 55 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![0, 6, 7, 8] ![1, 2, 3, 4, 5] d
    ((![![1, 0, 0, 0], ![1, 0, 0, 0], ![1, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase056 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 56) (cutOutside 56) d (cutCompatible 56 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 2, 3, 4] ![0, 5, 6, 7, 8] d
    ((![![0, 0, 1, 0], ![1, 0, 0, 0], ![2, 2, 1, 0], ![1, 0, 2, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase057 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 57) (cutOutside 57) d (cutCompatible 57 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 2, 3, 5] ![0, 4, 6, 7, 8] d
    ((![![1, 0, 0, 0], ![0, 0, 0, 0], ![0, 2, 1, 0], ![2, 0, 1, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase058 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 58) (cutOutside 58) d (cutCompatible 58 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 2, 3, 6] ![0, 4, 5, 7, 8] d
    ((![![0, 0, 2, 0], ![0, 0, 0, 0], ![2, 2, 0, 0], ![0, 0, 1, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase059 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 59) (cutOutside 59) d (cutCompatible 59 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 2, 3, 7] ![0, 4, 5, 6, 8] d
    ((![![1, 0, 0, 0], ![1, 0, 2, 0], ![0, 2, 2, 0], ![2, 0, 1, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase060 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 60) (cutOutside 60) d (cutCompatible 60 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 2, 3, 8] ![0, 4, 5, 6, 7] d
    ((![![2, 0, 2, 0], ![2, 0, 1, 0], ![1, 2, 1, 0], ![2, 0, 1, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase061 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 61) (cutOutside 61) d (cutCompatible 61 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 2, 4, 5] ![0, 3, 6, 7, 8] d
    ((![![0, 2, 0, 0], ![0, 2, 0, 0], ![1, 1, 0, 0], ![0, 1, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase062 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 62) (cutOutside 62) d (cutCompatible 62 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 2, 4, 6] ![0, 3, 5, 7, 8] d
    ((![![0, 1, 0, 0], ![0, 1, 0, 0], ![2, 0, 0, 0], ![0, 1, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase063 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 63) (cutOutside 63) d (cutCompatible 63 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 2, 4, 7] ![0, 3, 5, 6, 8] d
    ((![![0, 2, 0, 0], ![2, 2, 0, 0], ![1, 1, 0, 0], ![0, 1, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

#check compatibleCase063

private theorem compatibleCase064 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 64) (cutOutside 64) d (cutCompatible 64 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 2, 4, 8] ![0, 3, 5, 6, 7] d
    ((![![2, 2, 0, 0], ![1, 0, 0, 0], ![0, 2, 0, 0], ![2, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase065 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 65) (cutOutside 65) d (cutCompatible 65 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 2, 5, 6] ![0, 3, 4, 7, 8] d
    ((![![1, 1, 0, 0], ![0, 0, 0, 0], ![1, 0, 0, 0], ![2, 1, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase066 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 66) (cutOutside 66) d (cutCompatible 66 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 2, 5, 7] ![0, 3, 4, 6, 8] d
    ((![![0, 2, 0, 0], ![2, 1, 0, 0], ![2, 2, 0, 0], ![1, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase067 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 67) (cutOutside 67) d (cutCompatible 67 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 2, 5, 8] ![0, 3, 4, 6, 7] d
    ((![![2, 1, 0, 0], ![2, 2, 0, 0], ![0, 1, 0, 0], ![2, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase068 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 68) (cutOutside 68) d (cutCompatible 68 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 2, 6, 7] ![0, 3, 4, 5, 8] d
    ((![![2, 0, 0, 0], ![1, 1, 0, 0], ![1, 2, 0, 0], ![2, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase069 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 69) (cutOutside 69) d (cutCompatible 69 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 2, 6, 8] ![0, 3, 4, 5, 7] d
    ((![![1, 2, 0, 0], ![1, 1, 0, 0], ![0, 1, 0, 0], ![1, 1, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase070 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 70) (cutOutside 70) d (cutCompatible 70 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 2, 7, 8] ![0, 3, 4, 5, 6] d
    ((![![1, 1, 0, 0], ![1, 1, 0, 0], ![0, 1, 0, 0], ![1, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase071 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 71) (cutOutside 71) d (cutCompatible 71 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 3, 4, 5] ![0, 2, 6, 7, 8] d
    ((![![2, 2, 0, 0], ![1, 2, 0, 0], ![0, 2, 0, 0], ![1, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase072 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 72) (cutOutside 72) d (cutCompatible 72 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 3, 4, 6] ![0, 2, 5, 7, 8] d
    ((![![2, 2, 0, 0], ![0, 0, 0, 0], ![2, 0, 0, 0], ![2, 1, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase073 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 73) (cutOutside 73) d (cutCompatible 73 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 3, 4, 7] ![0, 2, 5, 6, 8] d
    ((![![1, 2, 0, 0], ![2, 2, 0, 0], ![0, 1, 0, 0], ![2, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase074 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 74) (cutOutside 74) d (cutCompatible 74 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 3, 4, 8] ![0, 2, 5, 6, 7] d
    ((![![2, 0, 0, 0], ![2, 2, 0, 0], ![0, 1, 0, 0], ![2, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase075 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 75) (cutOutside 75) d (cutCompatible 75 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 3, 5, 6] ![0, 2, 4, 7, 8] d
    ((![![2, 0, 0, 0], ![1, 1, 0, 0], ![1, 0, 0, 0], ![0, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase076 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 76) (cutOutside 76) d (cutCompatible 76 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 3, 5, 7] ![0, 2, 4, 6, 8] d
    ((![![2, 1, 0, 0], ![1, 0, 0, 0], ![1, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase077 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 77) (cutOutside 77) d (cutCompatible 77 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 3, 5, 8] ![0, 2, 4, 6, 7] d
    ((![![2, 1, 0, 0], ![1, 2, 0, 0], ![1, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase078 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 78) (cutOutside 78) d (cutCompatible 78 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 3, 6, 7] ![0, 2, 4, 5, 8] d
    ((![![2, 1, 0, 0], ![2, 0, 0, 0], ![1, 0, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase079 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 79) (cutOutside 79) d (cutCompatible 79 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 3, 6, 8] ![0, 2, 4, 5, 7] d
    ((![![0, 2, 0, 0], ![2, 0, 0, 0], ![1, 1, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

#check compatibleCase079

private theorem compatibleCase080 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 80) (cutOutside 80) d (cutCompatible 80 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 3, 7, 8] ![0, 2, 4, 5, 6] d
    ((![![0, 1, 0, 0], ![2, 0, 0, 0], ![1, 0, 0, 0], ![1, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase081 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 81) (cutOutside 81) d (cutCompatible 81 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 4, 5, 6] ![0, 2, 3, 7, 8] d
    ((![![1, 0, 0, 0], ![0, 0, 0, 0], ![1, 0, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase082 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 82) (cutOutside 82) d (cutCompatible 82 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 4, 5, 7] ![0, 2, 3, 6, 8] d
    ((![![0, 0, 0, 0], ![1, 0, 0, 0], ![1, 0, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase083 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 83) (cutOutside 83) d (cutCompatible 83 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 4, 5, 8] ![0, 2, 3, 6, 7] d
    ((![![2, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase084 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 84) (cutOutside 84) d (cutCompatible 84 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 4, 6, 7] ![0, 2, 3, 5, 8] d
    ((![![0, 0, 0, 0], ![2, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase085 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 85) (cutOutside 85) d (cutCompatible 85 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 4, 6, 8] ![0, 2, 3, 5, 7] d
    ((![![0, 0, 0, 0], ![2, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase086 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 86) (cutOutside 86) d (cutCompatible 86 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 4, 7, 8] ![0, 2, 3, 5, 6] d
    ((![![0, 0, 0, 0], ![2, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase087 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 87) (cutOutside 87) d (cutCompatible 87 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 5, 6, 7] ![0, 2, 3, 4, 8] d
    ((![![1, 0, 0, 0], ![1, 0, 0, 0], ![2, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase088 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 88) (cutOutside 88) d (cutCompatible 88 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 5, 6, 8] ![0, 2, 3, 4, 7] d
    ((![![1, 0, 0, 0], ![1, 0, 0, 0], ![2, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase089 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 89) (cutOutside 89) d (cutCompatible 89 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 5, 7, 8] ![0, 2, 3, 4, 6] d
    ((![![2, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase090 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 90) (cutOutside 90) d (cutCompatible 90 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![1, 6, 7, 8] ![0, 2, 3, 4, 5] d
    ((![![2, 0, 0, 0], ![2, 0, 0, 0], ![1, 0, 0, 0], ![1, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase091 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 91) (cutOutside 91) d (cutCompatible 91 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 3, 4, 5] ![0, 1, 6, 7, 8] d
    ((![![0, 2, 0, 0], ![2, 2, 0, 0], ![0, 0, 0, 0], ![0, 1, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase092 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 92) (cutOutside 92) d (cutCompatible 92 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 3, 4, 6] ![0, 1, 5, 7, 8] d
    ((![![0, 1, 0, 0], ![2, 2, 0, 0], ![0, 2, 0, 0], ![0, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase093 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 93) (cutOutside 93) d (cutCompatible 93 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 3, 4, 7] ![0, 1, 5, 6, 8] d
    ((![![0, 1, 0, 0], ![2, 1, 0, 0], ![0, 0, 0, 0], ![0, 1, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase094 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 94) (cutOutside 94) d (cutCompatible 94 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 3, 4, 8] ![0, 1, 5, 6, 7] d
    ((![![0, 2, 0, 0], ![2, 1, 0, 0], ![0, 1, 0, 0], ![0, 2, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase095 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 95) (cutOutside 95) d (cutCompatible 95 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 3, 5, 6] ![0, 1, 4, 7, 8] d
    ((![![0, 0, 0, 0], ![2, 1, 0, 0], ![0, 2, 0, 0], ![0, 1, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

#check compatibleCase095

private theorem compatibleCase096 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 96) (cutOutside 96) d (cutCompatible 96 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 3, 5, 7] ![0, 1, 4, 6, 8] d
    ((![![0, 0, 0, 0], ![2, 2, 0, 0], ![0, 1, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase097 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 97) (cutOutside 97) d (cutCompatible 97 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 3, 5, 8] ![0, 1, 4, 6, 7] d
    ((![![0, 0, 0, 0], ![2, 2, 0, 0], ![0, 1, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase098 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 98) (cutOutside 98) d (cutCompatible 98 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 3, 6, 7] ![0, 1, 4, 5, 8] d
    ((![![0, 0, 0, 0], ![2, 0, 0, 0], ![0, 2, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase099 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 99) (cutOutside 99) d (cutCompatible 99 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 3, 6, 8] ![0, 1, 4, 5, 7] d
    ((![![0, 0, 0, 0], ![2, 0, 0, 0], ![0, 2, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase100 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 100) (cutOutside 100) d (cutCompatible 100 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 3, 7, 8] ![0, 1, 4, 5, 6] d
    ((![![0, 2, 0, 0], ![2, 2, 0, 0], ![0, 2, 0, 0], ![0, 1, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase101 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 101) (cutOutside 101) d (cutCompatible 101 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 4, 5, 6] ![0, 1, 3, 7, 8] d
    ((![![2, 0, 0, 0], ![0, 0, 0, 0], ![2, 0, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase102 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 102) (cutOutside 102) d (cutCompatible 102 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 4, 5, 7] ![0, 1, 3, 6, 8] d
    ((![![2, 0, 0, 0], ![0, 0, 0, 0], ![1, 0, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase103 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 103) (cutOutside 103) d (cutCompatible 103 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 4, 5, 8] ![0, 1, 3, 6, 7] d
    ((![![1, 0, 0, 0], ![2, 0, 0, 0], ![1, 0, 0, 0], ![1, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase104 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 104) (cutOutside 104) d (cutCompatible 104 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 4, 6, 7] ![0, 1, 3, 5, 8] d
    ((![![0, 0, 0, 0], ![2, 0, 0, 0], ![2, 0, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase105 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 105) (cutOutside 105) d (cutCompatible 105 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 4, 6, 8] ![0, 1, 3, 5, 7] d
    ((![![2, 0, 0, 0], ![1, 0, 0, 0], ![1, 0, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase106 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 106) (cutOutside 106) d (cutCompatible 106 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 4, 7, 8] ![0, 1, 3, 5, 6] d
    ((![![1, 0, 0, 0], ![0, 0, 0, 0], ![1, 0, 0, 0], ![1, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase107 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 107) (cutOutside 107) d (cutCompatible 107 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 5, 6, 7] ![0, 1, 3, 4, 8] d
    ((![![0, 0, 0, 0], ![2, 0, 0, 0], ![2, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase108 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 108) (cutOutside 108) d (cutCompatible 108 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 5, 6, 8] ![0, 1, 3, 4, 7] d
    ((![![0, 0, 0, 0], ![2, 0, 0, 0], ![2, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase109 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 109) (cutOutside 109) d (cutCompatible 109 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 5, 7, 8] ![0, 1, 3, 4, 6] d
    ((![![0, 0, 0, 0], ![0, 0, 0, 0], ![1, 0, 0, 0], ![1, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase110 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 110) (cutOutside 110) d (cutCompatible 110 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![2, 6, 7, 8] ![0, 1, 3, 4, 5] d
    ((![![0, 0, 0, 0], ![0, 0, 0, 0], ![1, 0, 0, 0], ![1, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase111 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 111) (cutOutside 111) d (cutCompatible 111 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![3, 4, 5, 6] ![0, 1, 2, 7, 8] d
    ((![![0, 0, 0, 0], ![2, 0, 0, 0], ![2, 0, 0, 0], ![1, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

#check compatibleCase111

private theorem compatibleCase112 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 112) (cutOutside 112) d (cutCompatible 112 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![3, 4, 5, 7] ![0, 1, 2, 6, 8] d
    ((![![0, 0, 0, 0], ![0, 0, 0, 0], ![2, 0, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase113 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 113) (cutOutside 113) d (cutCompatible 113 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![3, 4, 5, 8] ![0, 1, 2, 6, 7] d
    ((![![1, 0, 0, 0], ![1, 0, 0, 0], ![0, 0, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase114 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 114) (cutOutside 114) d (cutCompatible 114 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![3, 4, 6, 7] ![0, 1, 2, 5, 8] d
    ((![![0, 0, 0, 0], ![0, 0, 0, 0], ![2, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase115 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 115) (cutOutside 115) d (cutCompatible 115 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![3, 4, 6, 8] ![0, 1, 2, 5, 7] d
    ((![![0, 0, 0, 0], ![0, 0, 0, 0], ![2, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase116 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 116) (cutOutside 116) d (cutCompatible 116 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![3, 4, 7, 8] ![0, 1, 2, 5, 6] d
    ((![![1, 0, 0, 0], ![1, 0, 0, 0], ![0, 0, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase117 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 117) (cutOutside 117) d (cutCompatible 117 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![3, 5, 6, 7] ![0, 1, 2, 4, 8] d
    ((![![0, 0, 0, 0], ![0, 0, 0, 0], ![2, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase118 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 118) (cutOutside 118) d (cutCompatible 118 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![3, 5, 6, 8] ![0, 1, 2, 4, 7] d
    ((![![0, 0, 0, 0], ![0, 0, 0, 0], ![2, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase119 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 119) (cutOutside 119) d (cutCompatible 119 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![3, 5, 7, 8] ![0, 1, 2, 4, 6] d
    ((![![1, 0, 0, 0], ![1, 0, 0, 0], ![2, 0, 0, 0], ![2, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase120 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 120) (cutOutside 120) d (cutCompatible 120 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![3, 6, 7, 8] ![0, 1, 2, 4, 5] d
    ((![![0, 0, 0, 0], ![2, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase121 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 121) (cutOutside 121) d (cutCompatible 121 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![4, 5, 6, 7] ![0, 1, 2, 3, 8] d
    ((![![0, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase122 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 122) (cutOutside 122) d (cutCompatible 122 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![4, 5, 6, 8] ![0, 1, 2, 3, 7] d
    ((![![0, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase123 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 123) (cutOutside 123) d (cutCompatible 123 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![4, 5, 7, 8] ![0, 1, 2, 3, 6] d
    ((![![0, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase124 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 124) (cutOutside 124) d (cutCompatible 124 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![4, 6, 7, 8] ![0, 1, 2, 3, 5] d
    ((![![0, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

private theorem compatibleCase125 : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected 125) (cutOutside 125) d (cutCompatible 125 *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels ![5, 6, 7, 8] ![0, 1, 2, 3, 4] d
    ((![![0, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0]] : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

theorem fastCompatible_cancels : ∀ (k : Fin 126) (d : Difference),
    d ≠ 0 → Cancels (cutSelected k) (cutOutside k) d (cutCompatible k *ᵥ d) := by
  intro k
  fin_cases k
  · exact compatibleCase000
  · exact compatibleCase001
  · exact compatibleCase002
  · exact compatibleCase003
  · exact compatibleCase004
  · exact compatibleCase005
  · exact compatibleCase006
  · exact compatibleCase007
  · exact compatibleCase008
  · exact compatibleCase009
  · exact compatibleCase010
  · exact compatibleCase011
  · exact compatibleCase012
  · exact compatibleCase013
  · exact compatibleCase014
  · exact compatibleCase015
  · exact compatibleCase016
  · exact compatibleCase017
  · exact compatibleCase018
  · exact compatibleCase019
  · exact compatibleCase020
  · exact compatibleCase021
  · exact compatibleCase022
  · exact compatibleCase023
  · exact compatibleCase024
  · exact compatibleCase025
  · exact compatibleCase026
  · exact compatibleCase027
  · exact compatibleCase028
  · exact compatibleCase029
  · exact compatibleCase030
  · exact compatibleCase031
  · exact compatibleCase032
  · exact compatibleCase033
  · exact compatibleCase034
  · exact compatibleCase035
  · exact compatibleCase036
  · exact compatibleCase037
  · exact compatibleCase038
  · exact compatibleCase039
  · exact compatibleCase040
  · exact compatibleCase041
  · exact compatibleCase042
  · exact compatibleCase043
  · exact compatibleCase044
  · exact compatibleCase045
  · exact compatibleCase046
  · exact compatibleCase047
  · exact compatibleCase048
  · exact compatibleCase049
  · exact compatibleCase050
  · exact compatibleCase051
  · exact compatibleCase052
  · exact compatibleCase053
  · exact compatibleCase054
  · exact compatibleCase055
  · exact compatibleCase056
  · exact compatibleCase057
  · exact compatibleCase058
  · exact compatibleCase059
  · exact compatibleCase060
  · exact compatibleCase061
  · exact compatibleCase062
  · exact compatibleCase063
  · exact compatibleCase064
  · exact compatibleCase065
  · exact compatibleCase066
  · exact compatibleCase067
  · exact compatibleCase068
  · exact compatibleCase069
  · exact compatibleCase070
  · exact compatibleCase071
  · exact compatibleCase072
  · exact compatibleCase073
  · exact compatibleCase074
  · exact compatibleCase075
  · exact compatibleCase076
  · exact compatibleCase077
  · exact compatibleCase078
  · exact compatibleCase079
  · exact compatibleCase080
  · exact compatibleCase081
  · exact compatibleCase082
  · exact compatibleCase083
  · exact compatibleCase084
  · exact compatibleCase085
  · exact compatibleCase086
  · exact compatibleCase087
  · exact compatibleCase088
  · exact compatibleCase089
  · exact compatibleCase090
  · exact compatibleCase091
  · exact compatibleCase092
  · exact compatibleCase093
  · exact compatibleCase094
  · exact compatibleCase095
  · exact compatibleCase096
  · exact compatibleCase097
  · exact compatibleCase098
  · exact compatibleCase099
  · exact compatibleCase100
  · exact compatibleCase101
  · exact compatibleCase102
  · exact compatibleCase103
  · exact compatibleCase104
  · exact compatibleCase105
  · exact compatibleCase106
  · exact compatibleCase107
  · exact compatibleCase108
  · exact compatibleCase109
  · exact compatibleCase110
  · exact compatibleCase111
  · exact compatibleCase112
  · exact compatibleCase113
  · exact compatibleCase114
  · exact compatibleCase115
  · exact compatibleCase116
  · exact compatibleCase117
  · exact compatibleCase118
  · exact compatibleCase119
  · exact compatibleCase120
  · exact compatibleCase121
  · exact compatibleCase122
  · exact compatibleCase123
  · exact compatibleCase124
  · exact compatibleCase125

end AME96

#print axioms AME96.fastCompatible_cancels
