"""Transcribe the supplied four matrices into Lean; Lean checks their properties."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
proof = (ROOT / "evidence/AME_9_6_complete_proof_20260922.md").read_text()

def matrix(name):
    body = proof.split(name + r"=\begin{pmatrix}", 1)[1].split(r"\end{pmatrix}", 1)[0]
    rows = [[int(x.strip()) for x in m.group().split("&")]
            for m in re.finditer(r"[012](?:\s*&\s*[012]){8}", body)]
    assert len(rows) == 9 and all(len(r) == 9 for r in rows)
    return "![" + ",\n  ".join("![" + ", ".join(map(str, r)) + "]" for r in rows) + "]"

text = '''import Mathlib.Data.Matrix.Basic
import Mathlib.Data.ZMod.Basic
import Mathlib.Tactic.FinCases

/-! Exact data from AME_9_6_complete_proof_20260922.md.
Generated by scripts/generate_data.py. No numerical approximations. -/
set_option maxRecDepth 8192
namespace AME96
open scoped BigOperators

'''
for name in ("G", "B", "H", "C"):
    modulus = 2 if name == "G" else 3
    text += f"def {name} : Matrix (Fin 9) (Fin 9) (ZMod {modulus}) :=\n  {matrix(name)}\n\n"
for name in ("G", "H", "C"):
    text += f"theorem {name}_symmetric (i j : Fin 9) : {name} i j = {name} j i := by\n  fin_cases i <;> fin_cases j <;> rfl\n"
    text += f"theorem {name}_diagonal : ∀ i, {name} i i = 0 := by decide +kernel\n"
text += "\nend AME96\n"
(ROOT / "AME96/Data.lean").write_text(text)
print("Generated AME96/Data.lean from the supplied proof.")
