"""Specialize each small finite check before kernel reduction."""
from pathlib import Path
root=Path(__file__).resolve().parents[1]
from generate_cuts import selected, outside, compatible, vec
out='''import AME96.CutData

/-! Generated by scripts/generate_fast_checks.py. Each proof specializes the
finite data before invoking the kernel, avoiding repeated indexing of the big table. -/
namespace AME96
open Matrix
set_option maxHeartbeats 0
set_option maxRecDepth 65536

'''
for k,(s,o,E) in enumerate(zip(selected,outside,compatible)):
    out+=f'''private theorem compatibleCase{k:03d} : ∀ d : Difference, d ≠ 0 →
    Cancels (cutSelected {k}) (cutOutside {k}) d (cutCompatible {k} *ᵥ d) := by
  change ∀ d : Difference, d ≠ 0 → Cancels {vec(s)} {vec(o)} d
    (({vec(E)} : Matrix (Fin 4) (Fin 4) (ZMod 3)) *ᵥ d)
  decide +kernel

'''
    if k % 16 == 15: out+=f'#check compatibleCase{k:03d}\n\n'
out+='''theorem fastCompatible_cancels : ∀ (k : Fin 126) (d : Difference),
    d ≠ 0 → Cancels (cutSelected k) (cutOutside k) d (cutCompatible k *ᵥ d) := by
  intro k
  fin_cases k
'''
for k in range(126): out+=f'  · exact compatibleCase{k:03d}\n'
out+='\nend AME96\n\n#print axioms AME96.fastCompatible_cancels\n'
(root/'AME96/FastChecks.lean').write_text(out)
print('Generated 126 specialized kernel checks.')
