"""Generate all 126 small certificates. Lean verifies all generated claims."""
from pathlib import Path
from itertools import combinations
import re
ROOT = Path(__file__).resolve().parents[1]
proof = (ROOT / 'evidence/AME_9_6_complete_proof_20260922.md').read_text()
def mat(name):
    body = proof.split(name + r'=\begin{pmatrix}', 1)[1].split(r'\end{pmatrix}', 1)[0]
    return [[int(x.strip()) for x in m.group().split('&')]
            for m in re.finditer(r'[012](?:\s*&\s*[012]){8}', body)]
C, B = mat('C'), mat('B')
def inverse(a):
    a = [row[:] + [int(i == j) for j in range(4)] for i, row in enumerate(a)]
    for j in range(4):
        pivot = next((i for i in range(j,4) if a[i][j] % 3), None)
        if pivot is None: return None
        a[j], a[pivot] = a[pivot], a[j]
        scale = pow(a[j][j], -1, 3)
        a[j] = [x*scale % 3 for x in a[j]]
        for i in range(4):
            if i != j:
                x = a[i][j]
                a[i] = [(u-x*v) % 3 for u,v in zip(a[i],a[j])]
    return [row[4:] for row in a]
def vec(x):
    if isinstance(x, (tuple,list)): return '![' + ', '.join(map(vec,x)) + ']'
    return str(x)
selected, outside, inverses, compatible = [], [], [], []
for s in combinations(range(9),4):
    o = [i for i in range(9) if i not in s]
    c = [[C[i][j] for j in s] for i in o]
    for rows in combinations(range(5),4):
        inv = inverse([c[i] for i in rows])
        if inv is not None: break
    assert inv is not None
    L = [[inv[j][rows.index(i)] if i in rows else 0 for i in range(5)] for j in range(4)]
    T = [[B[j][i] for j in s] for i in o]
    E = [[-sum(L[i][k]*T[k][j] for k in range(5)) % 3 for j in range(4)] for i in range(4)]
    selected.append(s); outside.append(o); inverses.append(L); compatible.append(E)
assert len(selected) == 126
def write_cut_data():
    text = 'import AME96.Certificate\n\n/-! Generated by scripts/generate_cuts.py. All certificates are checked in AllCuts.lean. -/\nset_option maxRecDepth 65536\nnamespace AME96\n\n'
    for name, typ, entries in [('cutSelected','Selected',selected),('cutOutside','Outside',outside),
                              ('cutLeftInverse','Matrix (Fin 4) (Fin 5) (ZMod 3)',inverses),
                              ('cutCompatible','Matrix (Fin 4) (Fin 4) (ZMod 3)',compatible)]:
        text += f'def {name} : Fin 126 → {typ} :=\n  ![' + ',\n    '.join(map(vec,entries)) + ']\n\n'
    text += 'end AME96\n'
    (ROOT/'AME96/CutData.lean').write_text(text)
    print('Generated 126 cut certificates.')

if __name__ == '__main__':
    write_cut_data()
